development:
  adapter: postgresql
  encoding: unicode
  database: eduson_development
  pool: 5
  timeout: 5000
  username: difry
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: eduson_test
  pool: 5
  timeout: 5000
  username: difry
  password:
