# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2719929765a1f7c7bdb1819dc9687569a3ce2f9d8ebef6493510721b8b9a72c3e5c6f2c8d142efbab80a5cf10ff32db119fe26a3d68b2486d589f153d998d0d9

test:
  secret_key_base: 7d7e63a5d7ac1f0ee60d689fb96952b8635648ef01ae96784d8a873137521fd3210f0b18dcdcef1b732a50d91a0713d1d8f5c55c682c7c93a7f450bbee4b6850

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
